# Generated by Django 4.2.30 on 2026-05-19 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('voice_id', models.CharField(max_length=100)),
                ('speed', models.FloatField(default=1.0)),
                ('volume', models.FloatField(default=1.0)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('file_format', models.CharField(default='mp3', max_length=10)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
